config/routes.rb
Rails.application.routes.draw do
  get 'tasksuasers/create'
  root to: 'tasks#index'
  resources :tasks do
    resources :tasksusers, only: [:create, :update]
  end
  resources :tasksusers, only: :index

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
end

app/models/task.rb
class Task < ApplicationRecord
  has_and_belongs_to_many :users
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :total_completed

  # GET /tasks
  # GET /tasks.json
  def index
    @tasksusers = TasksUsers.all
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @tasksusers = TasksUsers.all
    @user = User.all
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  def total_completed
    if signed_in?
      @tas = 0
      @tasksusers = TasksUsers.all
      @total_completed = @tasksusers.where(user_id: current_user.id)
      @total_completed.each do |total|
        @tas += 1 if total.completed == true
      end
   end
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:title, :description, :photo)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class='field text-dark'>
    <%= form.label :title %>
    <%= form.text_field :title, class:'form-control ds-input w-30' %>
  </div>

  <div class='field text-dark'>
    <%= form.label :description %>
    <%= form.text_field :description, class:'form-control ds-input w-30' %>
  </div>

  <div class='field text-dark'>
    <%= form.label :photo %>
    <%= form.text_field :photo, class:'form-control ds-input w-30' %>
  </div>

  <div class="btn btn-success">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<div class='container'>
  <h1 class='text-dark'> Tareas </h1>
  <div class='row'>
    <% @tasks.each_slice(3) do |row| %>
      <% row.each do |task| %>
        <% tus = TasksUsers.find_by(user_id: current_user.id, task_id: task.id) %>
        <% if tus.nil? || (tus.nil? == false && tus.completed == false) %>
          <div class='col-md-4'>
            <div class='card text-white border-primary'>
              <%= image_tag task.photo, class:'card-img-top' %>
              <div class='body text-center'>
                <h5> <%= task.title %> </h5>
                <p> <%= task.description %> </p>
                <div class='btn-group' role='group' aria-label='Basic example'>
                  <%= link_to 'Ver', task_path(task), class:'btn btn-primary' %>
                  <% if tus.nil? %>
                    <%= link_to 'Completado', task_tasksusers_path(task), class:'btn btn-success', method: :post %>
                  <% else %>
                    <%= link_to 'Completado', task_tasksuser_path(task, tus) , class:'btn btn-success', method: :patch %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        <% elsif tus.nil? == false && tus.completed = true %>
          <div class='col-md-4'>
            <div class='card text-white border-primary'>
              <%= image_tag task.photo, class:'card-img-top' %>
              <div class='body text-center'>
                <h5> <%= task.title %> </h5>
                <p> <%= task.description %> </p>
                <div class='btn-group' role='group' aria-label='Basic example'>
                  <%= link_to 'Ver', task_path(task), class:'btn btn-primary' %>
                  <%= link_to 'NO Completado', task_tasksuser_path(task, tus), class:'btn btn-danger', method: :patch %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
      <div class='w-100 mt-2'> </div>
    <% end %>
    <%= link_to 'Nueva Tarea', new_task_path, class:'btn btn-info' %>
  </div>
</div>

app/views/tasks/new.html.erb
<h1 class='text-dark'>Nueva tarea</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path, class:'btn btn-outline-info float-left mr-3 mt-3' %>

app/views/tasks/show.html.erb
<div class='container'>
  <h1 class='text-dark'> Ranking </h1>
  <div class='row'>
    <div class='col-md-6 mb-4'>
      <div class='card text-white border-primary'>
        <ul class='list-group list-group-flush'>
          <p class='card-text'><%= image_tag @task.photo, class:'card-img-top' %></p>
          <li class='list-group-item d-flex justify-content-between align-items-center'>
            <h3 class='card-text'><%= @task.title %></h3>
            <p class='card-text'><%= @task.description %></p>
            <div class='btn-group' role='group' aria-label='Basic example'>
            </div>
          </li>
        </ul>
      </div>
    </div>
    <div class='col-md-6'>
      <% @counter = 1 %>
      <% @tasksusers = TasksUsers.all.where(task_id: @task.id) %>
      <% @tasksusers = @tasksusers.order(completed_at: :asc) %>
      <% @tasksusers.each do |tus| %>
      <div class='card text-white border-primary text-center mb-2'>
        <% if tus.completed_at != nil %>
          <div>
            <h4><%= @counter %>°. <%= User.find_by(id: tus.user_id).name %> <%= User.find_by(id: tus.user_id).lastname %></h4>
              <% @avatar = User.find_by(id: tus.user_id).avatar %>
              <%= image_tag @avatar, class:'img-fluid w-90 mr-3' %>
            <h5> Completado el  <%= tus.completed_at %> </h5>
            <% @counter += 1 %>
          </div>
          <% end %>
        </div>
      <% end%>
      <div class='w-100 mt-2'> </div>
    </div>
  </div>
</div>